import type { Session } from '@supabase/supabase-js';
import type { QuestionRow } from '@/lib/types';

/** Stable fake user id (UUID) for demo UI only — not a real auth.users row. */
export const DEMO_USER_ID = '00000000-0000-4000-8000-000000000001';

/** Primary questions (same copy as seed migration) for offline demo. */
export const DEMO_QUESTIONS: QuestionRow[] = [
  {
    id: 'VB-01',
    question: 'I think honesty is more important than kindness when giving someone feedback.',
    dimension: 'values',
    match_type: 'S',
    weight: 1.5,
    display_order: 1,
    variant_group: 'VB-01',
    is_primary: true,
  },
  {
    id: 'VB-02',
    question: "I feel strongly that people should keep their commitments, even when it's inconvenient.",
    dimension: 'values',
    match_type: 'S',
    weight: 1.5,
    display_order: 2,
    variant_group: 'VB-02',
    is_primary: true,
  },
  {
    id: 'VB-03',
    question: 'I believe personal growth should be an ongoing priority in life.',
    dimension: 'values',
    match_type: 'S',
    weight: 1.5,
    display_order: 3,
    variant_group: 'VB-03',
    is_primary: true,
  },
  {
    id: 'VB-04',
    question: 'I think people are fundamentally good and trustworthy until proven otherwise.',
    dimension: 'values',
    match_type: 'S',
    weight: 1.5,
    display_order: 4,
    variant_group: 'VB-04',
    is_primary: true,
  },
  {
    id: 'VB-05',
    question: 'Financial security is a top priority for me in how I make life decisions.',
    dimension: 'values',
    match_type: 'S',
    weight: 1.5,
    display_order: 5,
    variant_group: 'VB-05',
    is_primary: true,
  },
  {
    id: 'CS-01',
    question: "When I'm upset, I prefer to talk about it straight away rather than wait.",
    dimension: 'communication',
    match_type: 'S',
    weight: 1.3,
    display_order: 6,
    variant_group: 'CS-01',
    is_primary: true,
  },
  {
    id: 'CS-02',
    question: 'I like to think through my feelings before sharing them.',
    dimension: 'communication',
    match_type: 'S',
    weight: 1.3,
    display_order: 7,
    variant_group: 'CS-02',
    is_primary: true,
  },
  {
    id: 'CS-03',
    question: 'I express care through doing things for people more than through words.',
    dimension: 'communication',
    match_type: 'S',
    weight: 1.3,
    display_order: 8,
    variant_group: 'CS-03',
    is_primary: true,
  },
  {
    id: 'CS-04',
    question: 'I prefer straightforward conversations over hints and subtlety.',
    dimension: 'communication',
    match_type: 'S',
    weight: 1.3,
    display_order: 9,
    variant_group: 'CS-04',
    is_primary: true,
  },
  {
    id: 'CS-05',
    question: 'I check in on the people I care about often, even when nothing is wrong.',
    dimension: 'communication',
    match_type: 'S',
    weight: 1.3,
    display_order: 10,
    variant_group: 'CS-05',
    is_primary: true,
  },
  {
    id: 'ES-01',
    question: 'I find it easy to identify and name my own emotions.',
    dimension: 'emotional',
    match_type: 'S',
    weight: 1.2,
    display_order: 11,
    variant_group: 'ES-01',
    is_primary: true,
  },
  {
    id: 'ES-02',
    question: "I tend to feel other people's emotions strongly — their mood affects mine.",
    dimension: 'emotional',
    match_type: 'S',
    weight: 1.2,
    display_order: 12,
    variant_group: 'ES-02',
    is_primary: true,
  },
  {
    id: 'ES-03',
    question: 'I recover from disappointment or conflict fairly quickly.',
    dimension: 'emotional',
    match_type: 'S',
    weight: 1.2,
    display_order: 13,
    variant_group: 'ES-03',
    is_primary: true,
  },
  {
    id: 'ES-04',
    question: 'I need regular reassurance in close relationships to feel secure.',
    dimension: 'emotional',
    match_type: 'S',
    weight: 1.2,
    display_order: 14,
    variant_group: 'ES-04',
    is_primary: true,
  },
  {
    id: 'ES-05',
    question: "I find it easy to apologise when I've made a mistake.",
    dimension: 'emotional',
    match_type: 'S',
    weight: 1.2,
    display_order: 15,
    variant_group: 'ES-05',
    is_primary: true,
  },
  {
    id: 'LS-01',
    question: 'I prefer a structured, planned lifestyle over a spontaneous one.',
    dimension: 'lifestyle',
    match_type: 'S',
    weight: 1.0,
    display_order: 16,
    variant_group: 'LS-01',
    is_primary: true,
  },
  {
    id: 'LS-02',
    question: 'I recharge by spending time alone rather than with others.',
    dimension: 'lifestyle',
    match_type: 'S',
    weight: 1.0,
    display_order: 17,
    variant_group: 'LS-02',
    is_primary: true,
  },
  {
    id: 'LS-03',
    question: 'Physical activity and health are central to how I live my life.',
    dimension: 'lifestyle',
    match_type: 'S',
    weight: 1.0,
    display_order: 18,
    variant_group: 'LS-03',
    is_primary: true,
  },
  {
    id: 'LS-04',
    question: 'I prefer to spend money on experiences rather than things.',
    dimension: 'lifestyle',
    match_type: 'S',
    weight: 1.0,
    display_order: 19,
    variant_group: 'LS-04',
    is_primary: true,
  },
  {
    id: 'LS-05',
    question: 'I like my living and working spaces to be tidy and organised.',
    dimension: 'lifestyle',
    match_type: 'S',
    weight: 1.0,
    display_order: 20,
    variant_group: 'LS-05',
    is_primary: true,
  },
  {
    id: 'IP-01',
    question: "What's a snack or food that genuinely makes your day better?",
    dimension: 'individual',
    match_type: 'I',
    weight: 0,
    display_order: 21,
    variant_group: 'IP-01',
    is_primary: true,
  },
  {
    id: 'IP-02',
    question: 'How do you prefer to spend a completely free Saturday morning?',
    dimension: 'individual',
    match_type: 'I',
    weight: 0,
    display_order: 22,
    variant_group: 'IP-02',
    is_primary: true,
  },
  {
    id: 'IP-03',
    question: "What's the best way someone could support you when you're stressed?",
    dimension: 'individual',
    match_type: 'I',
    weight: 0,
    display_order: 23,
    variant_group: 'IP-03',
    is_primary: true,
  },
  {
    id: 'IP-04',
    question: "What's a small thing that you do regularly that brings you genuine comfort?",
    dimension: 'individual',
    match_type: 'I',
    weight: 0,
    display_order: 24,
    variant_group: 'IP-04',
    is_primary: true,
  },
  {
    id: 'IP-05',
    question: 'How do you like to celebrate good news — big or small?',
    dimension: 'individual',
    match_type: 'I',
    weight: 0,
    display_order: 25,
    variant_group: 'IP-05',
    is_primary: true,
  },
];

export function createDemoSession(): Session {
  const now = new Date().toISOString();
  return {
    access_token: 'demo',
    refresh_token: 'demo',
    expires_in: 86400,
    expires_at: Math.floor(Date.now() / 1000) + 86400,
    token_type: 'bearer',
    user: {
      id: DEMO_USER_ID,
      aud: 'authenticated',
      role: 'authenticated',
      email: 'demo@intentionalconnections.app',
      app_metadata: {},
      user_metadata: {},
      created_at: now,
      updated_at: now,
    },
  };
}

/** Next question in demo (no “once per day” limit). Mirrors production order, starting at CS-04 when empty. */
export function getNextDemoQuestion(
  questions: QuestionRow[],
  responses: { question_id: string }[],
): QuestionRow | null {
  const done = new Set(responses.map((r) => r.question_id));
  if (responses.length === 0) {
    const first = questions.find((q) => q.id === 'CS-04');
    if (first && !done.has(first.id)) {
      return first;
    }
  }
  const ordered = [...questions].sort((a, b) => a.display_order - b.display_order);
  const next = ordered.find((q) => !done.has(q.id));
  return next ?? null;
}
